apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: otus-kbalakin-ingress
spec:
  rules:
    - host: arch.homework
      http:
        paths:
          - path: /health
            pathType: Prefix
            backend:
              service:
                name: otus-kbalakin-service
                port:
                  number: 8000
          - path: /postgres
            pathType: Prefix
            backend:
              service:
                name: my-postgres-postgresql
                port:
                  number: 5432